# Reference

In [19]:
from IPython.display import IFrame
IFrame('https://www.yiibai.com/pandas/python_pandas_quick_start.html', width='80%', height=350)

First of all, Lets text if Pandas is successfully installed in our system

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello, Pandas")

Hello, Pandas


# To Creat an Object

通过传递值列表来创建一个系列:

In [4]:
import pandas as pd
import numpy as np

s = pd.Series([1,3,5,np.nan,6,8])

print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [8]:
import pandas as pd
import numpy as np

dates = pd.date_range('20181117',periods=7)
print(dates)

print('\n',"**"*16,'\n')

df = pd.DataFrame(np.random.randn(7,4), index = dates, columns = list('ABCD'))
print(df)

DatetimeIndex(['2018-11-17', '2018-11-18', '2018-11-19', '2018-11-20',
               '2018-11-21', '2018-11-22', '2018-11-23'],
              dtype='datetime64[ns]', freq='D')

 ******************************** 

                   A         B         C         D
2018-11-17  0.514832  0.778748 -0.191001 -1.123627
2018-11-18  1.698383 -0.088893 -0.576086 -0.207487
2018-11-19 -0.032073 -0.619432  0.110399  1.695459
2018-11-20  2.115899 -0.846220  1.041634  1.673890
2018-11-21  1.847953  0.174457 -0.493625 -1.528536
2018-11-22  0.168726  1.991569  1.706197  1.139672
2018-11-23 -1.271815 -0.959876  0.378239 -0.426116


通过传递可以转换为类似系列的对象的字典来创建DataFrame:

In [12]:
import pandas as pd
import numpy as np

df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20170102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })

print(df2)

     A          B    C  D      E    F
0  1.0 2017-01-02  1.0  3   test  foo
1  1.0 2017-01-02  1.0  3  train  foo
2  1.0 2017-01-02  1.0  3   test  foo
3  1.0 2017-01-02  1.0  3  train  foo


# To Check the Object

查看框架的顶部和底部的数据行

In [17]:
import pandas as pd
import numpy as np

dates = pd.date_range('20190101', periods=7)
df = pd.DataFrame(np.random.randn(7,4), index=dates, columns=list('ABCD'))
print(df.head(1))
print('\n',"--------------" * 5)
print(df.tail(3))
print('\n',"--------------" * 5)
print(df.head())
print('\n',"--------------" * 5)
print(df.tail())

                   A         B         C         D
2019-01-01  0.783824  0.658986  0.527428  0.211701

 ----------------------------------------------------------------------
                   A         B         C         D
2019-01-05  1.753305  0.370565  0.738523 -1.581296
2019-01-06 -1.443087  0.236154 -1.606436  0.247117
2019-01-07 -0.500745  0.031479 -0.545335  0.188678

 ----------------------------------------------------------------------
                   A         B         C         D
2019-01-01  0.783824  0.658986  0.527428  0.211701
2019-01-02  1.440106  2.030470  0.031809  0.894760
2019-01-03  0.454081 -0.128540 -1.373343  1.110446
2019-01-04  0.583133  0.072180  0.904044 -0.544867
2019-01-05  1.753305  0.370565  0.738523 -1.581296

 ----------------------------------------------------------------------
                   A         B         C         D
2019-01-03  0.454081 -0.128540 -1.373343  1.110446
2019-01-04  0.583133  0.072180  0.904044 -0.544867
2019-01-05  1.75

显示索引，列和底层numpy数据:

In [18]:
import pandas as pd
import numpy as np

dates = pd.date_range('20190101', periods=7)
df =pd.DataFrame(np.random.randn(7,4), index=dates, columns=list('ABCD'))

print("index is: \n")
print(df.index)

print("columns is: \n")
print(df.columns)

print("values is: \n")
print(df.values)

index is: 

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')
columns is: 

Index(['A', 'B', 'C', 'D'], dtype='object')
values is: 

[[-0.27559708  0.256468    1.54633015  1.17710659]
 [-0.17288087 -0.50793981 -0.96981305 -2.61249424]
 [ 2.02627549  0.08896899  0.73221054  0.22738   ]
 [ 0.42087467  0.89543443  1.06157508  1.70490708]
 [-0.96480652  0.6399674   0.44883617 -0.39064757]
 [-0.06631172 -1.2824176  -0.80144621  1.62907481]
 [ 0.01064595  1.66116434  1.99920962 -0.45010255]]


描述显示数据的快速统计摘要: